from typing import Dict, List


def build_investigation(
    risk_score: float,
    risk_level: str,
    evidence: List[str],
) -> Dict:
    """
    Build a structured risk investigation report.

    The agent receives evidence generated by deterministic
    RiskGuard components. It does not invent transaction facts.
    """

    if risk_level == "HIGH":
        recommended_action = "ESCALATE_FOR_REVIEW"
    elif risk_level == "MEDIUM":
        recommended_action = "MONITOR_AND_REVIEW"
    else:
        recommended_action = "ALLOW_WITH_MONITORING"

    if risk_level == "HIGH":
        summary = (
            "The transaction presents multiple elevated-risk "
            "indicators and should be reviewed by a risk analyst."
        )
    elif risk_level == "MEDIUM":
        summary = (
            "The transaction contains some risk indicators "
            "and should receive additional monitoring."
        )
    else:
        summary = (
            "The transaction does not currently show enough "
            "risk indicators to require escalation."
        )

    return {
        "risk_score": risk_score,
        "risk_level": risk_level,
        "summary": summary,
        "evidence": evidence,
        "recommended_action": recommended_action,
    }


def print_investigation(report: Dict):
    """Display a human-readable investigation report."""

    print("\n================================")
    print("     RISKGUARD INVESTIGATION")
    print("================================")

    print(f"\nRisk Score: {report['risk_score']}/100")
    print(f"Risk Level: {report['risk_level']}")

    print("\nSummary:")
    print(report["summary"])

    print("\nEvidence:")

    for number, item in enumerate(
        report["evidence"],
        start=1,
    ):
        print(f"{number}. {item}")

    print("\nRecommended Action:")
    print(report["recommended_action"])


if __name__ == "__main__":

    sample_evidence = [
        "Transaction amount is 7.08x the customer's average.",
        "Transaction occurred at 02:00, which is an unusual overnight transaction time.",
        "A new or unusual transaction location was detected.",
        "A new or unrecognized device was detected.",
        "Elevated transaction velocity detected: 6 recent transactions.",
        "2 previous risk event(s) are associated with this customer.",
    ]

    investigation = build_investigation(
        risk_score=94.89,
        risk_level="HIGH",
        evidence=sample_evidence,
    )

    print_investigation(investigation)